name: graduation_project
description: "Graduation project"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.8.1
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2
  path_provider: ^2.1.5
  flutter_quill: ^10.8.5
  url_launcher: ^6.3.1
  csv: ^6.0.0
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ius-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/ius-logo.png
    - assets/erasmus.png
    - assets/iro.jpeg
    - assets/scc.jpeg
    - assets/ius_wolves.jpeg
    - assets/internships.jpg
    - assets/calendar.png
    - assets/clubs.jpg
    - assets/fass.png
    - assets/fens.png
    - assets/fedu.png
    - assets/flw.png
    - assets/fba.png
